### PR TITLE
Added Demo Link in readme file

### PR DESCRIPTION
**Pull request by officialzubairansari**

### CODE REVIEW

**Review by shoaibshams — CHANGES_REQUESTED** [review]
Can you please make a subdomain like https://expense-tracker.laravelpakistan.com
Or
https://expense-tracker.demo.laravelpakistan.com

**Comment by shoaibshams** [comment]
Please import the dummy data in demo,
You can use DemoSeeder class to import data:
php artisan db:seed --class=DemoSeeder

**Comment by officialzubairansari** [comment]
I just want to host all open source projects into a single subdomain like os.laravelpakistan.com (just an idea),
project-name.demo.laravelpakistan.com is also a good idea.
Actually iam using cloudflare to poin domain to server, so I don't know how to point subdomain under subdomain in cloudflate, let me try, Once it is done I will let you know.


* yes I forgot to run seeder, Iam doing this now.

**Comment by officialzubairansari** [comment]
yes I have changes the url of demo with
https://expense-tracker.laravelpakistan.com 
and also runs php artisan db:seed --class=DemoSeeder

**Review by shoaibshams — APPROVED** [review]
Thanks

**Pull request merged**
